# Generated by Django 3.0 on 2020-06-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.TextField()),
                ('pname', models.TextField()),
                ('date', models.TextField()),
                ('time', models.TextField()),
                ('pres', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField()),
                ('mob', models.IntegerField()),
                ('age', models.IntegerField()),
                ('gen', models.CharField(max_length=50)),
                ('dis', models.TextField()),
            ],
        ),
    ]
